//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/quicapp/headers_and_frames/MaxDataFrame.msg.
//

#ifndef __INET_MAXDATAFRAME_M_H
#define __INET_MAXDATAFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class MaxDataFrame;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/applications/base/ApplicationPacket_m.h" // import inet.applications.base.ApplicationPacket

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/applications/quicapp/headers_and_frames/QuicFrame_m.h" // import inet.applications.quicapp.headers_and_frames.QuicFrame


namespace inet {

/**
 * Class generated from <tt>inet/applications/quicapp/headers_and_frames/MaxDataFrame.msg:25</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class MaxDataFrame extends QuicFrame
 * {
 *     //A MAX_DATA frame (type=0x10) is used in flow control to inform the peer of the maximum amount of data that
 *     //can be sent on the connection as a whole. (RFC 19.9)
 *     int maximum_data; // maximum amount of data that can be sent on the entire connection, in units of bytes
 * }
 * </pre>
 */
class INET_API MaxDataFrame : public ::inet::QuicFrame
{
  protected:
    int maximum_data = 0;

  private:
    void copy(const MaxDataFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MaxDataFrame&);

  public:
    MaxDataFrame();
    MaxDataFrame(const MaxDataFrame& other);
    virtual ~MaxDataFrame();
    MaxDataFrame& operator=(const MaxDataFrame& other);
    virtual MaxDataFrame *dup() const override {return new MaxDataFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getMaximum_data() const;
    virtual void setMaximum_data(int maximum_data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MaxDataFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MaxDataFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_MAXDATAFRAME_M_H

