//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/quicapp/headers_and_frames/QuicFrame.msg.
//

#ifndef __INET_QUICFRAME_M_H
#define __INET_QUICFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class QuicFrame;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/applications/base/ApplicationPacket_m.h" // import inet.applications.base.ApplicationPacket

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/applications/quicapp/headers_and_frames/QuicFrame.msg:24</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class QuicFrame extends FieldsChunk
 * {
 *     int frame_type;
 * }
 * </pre>
 */
class INET_API QuicFrame : public ::inet::FieldsChunk
{
  protected:
    int frame_type = 0;

  private:
    void copy(const QuicFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QuicFrame&);

  public:
    QuicFrame();
    QuicFrame(const QuicFrame& other);
    virtual ~QuicFrame();
    QuicFrame& operator=(const QuicFrame& other);
    virtual QuicFrame *dup() const override {return new QuicFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFrame_type() const;
    virtual void setFrame_type(int frame_type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QuicFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QuicFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_QUICFRAME_M_H

