//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/quicapp/headers_and_frames/StreamDataBlockedFrame.msg.
//

#ifndef __INET_STREAMDATABLOCKEDFRAME_M_H
#define __INET_STREAMDATABLOCKEDFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class StreamDataBlockedFrame;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/applications/base/ApplicationPacket_m.h" // import inet.applications.base.ApplicationPacket

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/applications/quicapp/headers_and_frames/QuicFrame_m.h" // import inet.applications.quicapp.headers_and_frames.QuicFrame


namespace inet {

/**
 * Class generated from <tt>inet/applications/quicapp/headers_and_frames/StreamDataBlockedFrame.msg:25</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class StreamDataBlockedFrame extends QuicFrame
 * {
 *     //A sender SHOULD send a STREAM_DATA_BLOCKED frame (type=0x15) when it wishes to send data, but is unable to 
 *     //do so due to stream-level flow control. This frame is analogous to DATA_BLOCKED. (RFC 19.13)
 *     int stream_id; // the stream that is blocked due to flow control
 *     int maximum_stream_data; // the offset of the stream at which the blocking occurred
 * }
 * </pre>
 */
class INET_API StreamDataBlockedFrame : public ::inet::QuicFrame
{
  protected:
    int stream_id = 0;
    int maximum_stream_data = 0;

  private:
    void copy(const StreamDataBlockedFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StreamDataBlockedFrame&);

  public:
    StreamDataBlockedFrame();
    StreamDataBlockedFrame(const StreamDataBlockedFrame& other);
    virtual ~StreamDataBlockedFrame();
    StreamDataBlockedFrame& operator=(const StreamDataBlockedFrame& other);
    virtual StreamDataBlockedFrame *dup() const override {return new StreamDataBlockedFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getStream_id() const;
    virtual void setStream_id(int stream_id);
    virtual int getMaximum_stream_data() const;
    virtual void setMaximum_stream_data(int maximum_stream_data);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StreamDataBlockedFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StreamDataBlockedFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_STREAMDATABLOCKEDFRAME_M_H

