//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/quicapp/headers_and_frames/StreamFrame.msg.
//

#ifndef __INET_STREAMFRAME_M_H
#define __INET_STREAMFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class StreamFrame;
} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/applications/base/ApplicationPacket_m.h" // import inet.applications.base.ApplicationPacket

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/applications/quicapp/headers_and_frames/QuicFrame_m.h" // import inet.applications.quicapp.headers_and_frames.QuicFrame


namespace inet {

/**
 * Class generated from <tt>inet/applications/quicapp/headers_and_frames/StreamFrame.msg:25</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * class StreamFrame extends QuicFrame
 * {
 *     int stream_id; // stream ID of the stream
 *     int offset; // the byte offset in the stream for the data in this STREAM frame
 *     int length; // length of the Stream Data field in this STREAM frame
 *     bool is_FIN;
 * }
 * </pre>
 */
class INET_API StreamFrame : public ::inet::QuicFrame
{
  protected:
    int stream_id = 0;
    int offset = 0;
    int length = 0;
    bool is_FIN = false;

  private:
    void copy(const StreamFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const StreamFrame&);

  public:
    StreamFrame();
    StreamFrame(const StreamFrame& other);
    virtual ~StreamFrame();
    StreamFrame& operator=(const StreamFrame& other);
    virtual StreamFrame *dup() const override {return new StreamFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getStream_id() const;
    virtual void setStream_id(int stream_id);
    virtual int getOffset() const;
    virtual void setOffset(int offset);
    virtual int getLength() const;
    virtual void setLength(int length);
    virtual bool getIs_FIN() const;
    virtual void setIs_FIN(bool is_FIN);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const StreamFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, StreamFrame& obj) {obj.parsimUnpack(b);}

} // namespace inet

#endif // ifndef __INET_STREAMFRAME_M_H

